//Even Fibonacci numbers
//Problem 2
//Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
//By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million,
// find the sum of the even-valued terms.


/*-----Solution Provided by ------
-------Lilian Kotvan -----------*/

public class Problem2{

	public static void main (String[] args){
		int fibonacci = 0;
		int incremento = 1;
		int sum = 0;
		
		while (fibonacci <= 4000000 || incremento <= 4000000){
			fibonacci += incremento;
			incremento += fibonacci;

			if((fibonacci % 2) == 0){
				sum += fibonacci;
			}else if((incremento %2) == 0){
				sum += incremento;
			}
		}
		System.out.println("A soma é: " + sum);
	}
}
			
			


